### ISSUE TITLE
Question: Why do you think this may not work for Mongoose 4.x?

### ISSUE THREAD

**Issue by mjfalkenstein** [iliakan/cls-mongoose#5]
I'd like to use this tool with mongoose 4.9, and knowing the details why you think this might not work could be really helpful.

Thanks!

**Comment by iliakan** [comment]
Don't use CLS. It sucks.

**Comment by jyoung-asymmetrik** [comment]
Just wanted to update this ticket with what we ended up doing. Since mongoose has been changed to use a promise library (we are using Q), we found that adding cls-q to patch q seems to fix mongoose too. We'll be testing some more, but wanted to let you know in case that was useful. Thanks for your help!
